[project]
name = "ruff-v1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fady atia", email = "fadyatia375@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
ruff-v1 = "ruff_v1:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.8",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I"]